default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  timeout: 5000
  url:  <%= ENV.fetch("AACT_PROJ_DATABASE_URL", "") %>

development:
  <<: *default
  url:  <%= ENV.fetch("AACT_PROJ_DATABASE_URL", "") %>

test:
  <<: *default
  database: aact_back_test

production:
  <<: *default
  url:  <%= ENV.fetch("AACT_PROJ_DATABASE_URL", "") %>
